Feature
Volkov190/Hacker pull request #1
Opened 2022-06-23 19:09 UTC by Volkov190

2022-07-19 19:03 UTC, crutch12 commented
отдал @stilwuc

2022-07-21 11:12 UTC, Stilwuc requested changes
Неплохо
Поправь селекторы по классам, лучше заюзай RTK query, и еще пару минимальный вещей и будет хорошо)
А ну и закинь плз на codesandbox, а то на локале лень разворачиваться

2022-07-21 11:12 UTC, Stilwuc commented on package.json
> +    "react-router-dom": "^6.3.0"
Правильней это не в devDeps закидывать(хоть и на сборку не повлияет). Для лучшей читаемости настоящих зависимостей)

2022-07-21 11:12 UTC, Stilwuc commented on src/react-app-env.d.ts
> +// / <reference types="react-scripts" />
А зачем?)

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +    // console.log(comment);
Забыл убрать

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +  } else return <></>;
Лучше вместо пустого фрагмента `<></>` писать null, читается легче, и допускается такое возвращать как пустой рендер

2022-07-21 11:12 UTC, Stilwuc commented on src/interfaces/singleNews.ts
> +export default interface singleNews {
Интерфейсы и типы пишем в PascalCase(для узнаваемости), поэтому тут будет `SingleNews`

2022-07-21 11:12 UTC, Stilwuc commented on src/interfaces/aPieceOfNews.ts
> +export default interface aPieceOfNews {
Не хочу особо докапываться к названию переменных и интерфейсов, просто разок напишу, и тут сам думай хочешь править или нет)
Вообщем советую серьезно подходить к наименованию переменных, во первых они должны быть простые, без всяких лишних слов/предлогов(тут например я бы убил артикль `a`)
И они не должны быть слишком абстрактные, как например у тебя есть `Item`, нужно чтобы название говорило что за тип/сущность в нем лежит
А ну и не нужно сокращать переменные так, что непонятно что под этим подрузамевается (`showAns` например)

2022-07-21 11:12 UTC, Stilwuc commented on src/interfaces/aPieceOfNews.ts
> +  rating: number | null | undefined;
Лучше юзать `?` чем явный undefined, если это не обусловлено тем что ты реально ожидаешь undefined тип, так короче и легче читать

2022-07-21 11:12 UTC, Stilwuc commented on src/interfaces/IComment.ts
> +export default interface IComment {
Префиксы типа `I` не стоит юзать, в TS сообществе считается не очень практикой, тем более в других интерфейсах ты не делал этот префикс

2022-07-21 11:12 UTC, Stilwuc commented on src/index.tsx
> -  <React.StrictMode>
StrictMode лучше оставить, позволяет избежать некоторых ошибок при разработке
https://ru.reactjs.org/docs/strict-mode.html

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +    axios(`https://api.hnpwa.com/v0/item/${props.id}.json`).then((resp) => {
Если StrictMode вернешь будь готов что это будет вызываться дважды.
https://github.com/facebook/react/issues/24502#issuecomment-1121089680
Советую в данном случае просто переехать на `RTK Query`

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +  if (comment) {
В таких ситуациях лучше делать ранний выход из функции(компонента), типо такого
```
if (!comment) return null;

return (
  <>
     <Wrapper className="commentWrapper"
...
```
А еще лучше вместо Null какой нибудь лоадер выводить, пользаку будет понятно что грузятся данные

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +          className="commentWrapper"
Зачем классы, выглядит как будто при переходе на styled забыл их выпилить

2022-07-21 11:12 UTC, Stilwuc commented on src/App.tsx
> +        <Route path="/news" element={<NewsPage />}></Route>
При проверке как то получил проблему о дублях `key`, описал в https://github.com/Volkov190/Hacker/pull/1#discussion_r926548384
Но если будет время можешь подумать/посмотреть как такое могло получится
![image](https://user-images.githubusercontent.com/44724024/180181209-8b9d053b-0f89-45ce-9058-e10ef38b3c20.png)

2022-07-21 11:12 UTC, Stilwuc commented on src/components/Comment.tsx
> +  & .content {
Лучше вместо селектора по классу делать селектор по другому `styled` компоненту

2022-07-21 11:12 UTC, Stilwuc commented on src/App.tsx
> +        <Route path="/" element={<Navigate to="/news" replace />}></Route>
```suggestion
        <Route path="/" element={<Navigate to="/news" replace />} />
```

2022-07-21 11:12 UTC, Stilwuc commented on src/components/PieceOfNews.tsx
> +      style={{ textDecoration: 'none', display: 'block' }}
Лучше это в styled вынести

2022-07-21 11:12 UTC, Stilwuc commented on src/components/PieceOfNews.tsx
> +export { PieceOfNews };
Интересный export)
Обычно так, ты либо всегда export default делаешь компонентов, либо просто export, оборачивать перед этим в объект не надо

2022-07-21 11:12 UTC, Stilwuc commented on src/slices/newsSlice.tsx
> +        state.count = state.news.length;
А зач сохранять в стейте count, если ты можешь его сам всегда получить через state.news.length

2022-07-21 11:12 UTC, Stilwuc commented on src/slices/newsSlice.tsx
> +  news: Array<FeedItem>;
Лучше короткий синтаксис типизации массива
```suggestion
  news: FeedItem[];
```

2022-07-21 11:12 UTC, Stilwuc commented on src/pages/SingleNewsPage.tsx
> +        } else goNotFound();
Дублирование кода по получению инфы тут выше, и ниже в render функции.
Лучше вынести в отдельную подфункцию.
Но еще лучше заюзать RTK query, там и inteval для обновления информации можно настроить изи

2022-07-21 11:12 UTC, Stilwuc commented on src/pages/SingleNewsPage.tsx
> +    } else {
Вместо вложенных if'ов тоже лучше юзать ранние выходы
```
if (isNaN(id)) return goNotFound();
...
```
Меньше вложенностей => легче читать

2022-07-21 11:12 UTC, Stilwuc commented on src/pages/NewsPage.tsx
> +          if (newsCount > 0) {
Вот тут кстати прикол как раз с дублированием ключей)
Так как ты постепенно подгружаешь по одному блоку новостей(из 30 элементов), можно поймать случай при котором у тебя прогрузился только один блок, но я уже могу нажать обновить(даже без тротлинга инета) и получится небольшой конфликт данных).
Думаю просто решение здесь дождаться когда загрузится все блоки новостей и после этого отображать их

2022-07-22 15:53 UTC, Volkov190 commented
по коду вроде всё поправил

2022-07-22 16:13 UTC, Volkov190 commented
по поводу CORS на gh-pages не понял что не так, просто заново задеплоил, вот [codesandbox](https://codesandbox.io/s/hacker-epsdge?file=/src/App.tsx) на всякий случай

2022-07-23 18:46 UTC, crutch12 commented
я вроде не просил gh pages, ну да ладно

2022-07-25 09:13 UTC, Stilwuc reviewed
Нормас, все комменты поправил, тут еще парочку небольших замечаний подвалило, большая часть не важная, но если поправишь будет хорошо)

2022-07-25 09:13 UTC, Stilwuc commented on src/components/Comment.tsx
> +export const Comment = (props: { commentId: number; commentLevel: number }) => {
Если у тебя React 18 то после ласт лекции как я понял идем по такой теме:

- Юзаем `FC` если компонент не generic
- Если компонент generic юзаем типизацию аргумента функции

Не крит замечания, и если сейчас ничего еще не всплывет можно игнорить)
Но на будущее делаем так

2022-07-25 09:13 UTC, Stilwuc commented on src/components/Comment.tsx
> +    if (!isLoading) setComment(data);
А зачем делать отдельный стейт для хранения информации о комменте, если ты можешь на прямую юзать `data`

2022-07-25 09:13 UTC, Stilwuc commented on src/components/Comment.tsx
> +        {!isLoading && typeof comment !== 'undefined' ? (
Мне кажется правильней тут даже не рендерить `<Wrapper>` пока не загрузим коммент.
А то чисто теоретически можно нажать раскрыть вложенные комменты.
Т.е. сделать ранний выход из функции с `'Loading...'`

2022-07-25 09:13 UTC, Stilwuc commented on src/components/Comment.tsx
> +              {comment.comments_count > 0 ? <p>Ответов: {comment.comments_count}</p> : null}
Можно короче)
```suggestion
              {comment.comments_count > 0 && <p>Ответов: {comment.comments_count}</p>}
```

2022-07-25 09:13 UTC, Stilwuc commented on src/components/Frame.tsx
> +  & a {
`&` здесь необязательно писать, так как в данном случае твой селектор будет совпадать с просто `a`, за исключением если ты не хочешь добавить веса своему селектору для переопределения стилей(тут вроде не этот кейс)

2022-07-25 09:13 UTC, Stilwuc commented on src/react-app-env.d.ts
> -/// <reference types="react-scripts" />
Когда я спрашивал зачем имел ввиду пробел между слешами)
Сам файл то лучше оставить, а то типизация на всякие svg импорт не будет

2022-07-25 09:13 UTC, Stilwuc commented on src/icons/ChevronLeft.tsx
> +export const ChevronLeft = () => {
В принципе допустима такая работа с свг, но если что есть тема по лучше, называется `svgr`.
Позволяет хранить `.svg` формате, и работать с ними как с react компонентами при импорте.
В `CRA` по дефолту такая тема настроена

2022-07-25 09:13 UTC, Stilwuc commented on src/components/UpdateButton.tsx
> +const UpdateButton = (props: { onClick: () => void; className?: string }) => {
inline типизация ок, но лучше начиная с 2-3 ключей выкидывать в отдельный интерфейс, легче читается

2022-07-25 09:13 UTC, Stilwuc commented on src/pages/NewsPage.tsx
> +  & ${StyledPieceOfNews} {
Тут тоже амперсанты не нужны

2022-07-25 09:13 UTC, Stilwuc commented on src/pages/SingleNewsPage.tsx
> +  let dateStr = '';
Странная иницилизация переменной. Типо let с пустой строкой, чтобы потом на некст строке задать значение.

2022-07-25 09:13 UTC, Stilwuc commented on src/pages/SingleNewsPage.tsx
> +    const interval = setInterval(refetch, 60000);
Вот эти штуки если что можно сделать с использованием `RTC Query`
https://redux-toolkit.js.org/rtk-query/usage/queries#query-hook-options
![image](https://user-images.githubusercontent.com/44724024/180740455-37481027-c1d3-46c4-96b4-f451e5034ba5.png)

2022-07-25 09:13 UTC, Stilwuc commented on src/services/news.ts
> +      async queryFn(_arg, _queryApi, _extraOptions, fetchWithBQ) {
Названия переменных с `_` обычно означают то что мы их не юзаем, а в твоем случае тот же `_arg` ты юзаешь на 21 строчке, так что лучше назови просто arg а еще лучше более конкретно (`pageSize` у тебя вроде)

2022-07-25 09:13 UTC, Stilwuc commented on src/services/news.ts
> +        while (newsCount < _arg) {
Опять же можешь не создавать отдельную переменную для хранения длины массива, а просто высчитывать её
```suggestion
        while (results.length< _arg) {
```

2022-07-25 11:59 UTC, Volkov190 commented
поправил

2022-07-25 14:22 UTC, Stilwuc approved these changes

2022-07-25 17:23 UTC, Stilwuc commented
@Volkov190 Можешь мержить)

2022-07-25 17:56 UTC, merged